[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read", path = "./broadcast" }]
remappings = [
  '@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/',
]

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
multiline_func_header = "attributes_first"
quote_style = "double"
number_underscore = "thousands"

[lint]
exclude_lints = ["mixed-case-variable", "screaming-snake-case-immutable"]

[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
